# Generated by Django 5.2 on 2025-04-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars_vw', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user')),
                ('shop_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('warranty', models.IntegerField(default=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cars_vw.car')),
            ],
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='users.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='users.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='cars_vw.car')),
            ],
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='users.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='users.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='cars_vw.car')),
            ],
        ),
    ]
