# Generated by Django 5.2 on 2025-04-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_client_alter_rents_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(),
        ),
    ]
