# Generated by Django 5.2 on 2025-04-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_shop_address_alter_order_number'),
        ('users', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.address'),
        ),
    ]
