# Generated by Django 5.2 on 2025-05-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_shop_address_alter_orderline_quantity'),
        ('orders', '0005_remove_orderline_quantity_alter_order_shop_address'),
    ]

    operations = [
    ]
