# Generated by Django 5.2 on 2025-04-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('c_for', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('num_seats', models.IntegerField()),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='car_pictures/')),
            ],
            options={
                'ordering': ('name', 'num_seats', 'c_for'),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.BooleanField(default=False)),
                ('established', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('designation', models.BooleanField(default=False)),
                ('test_drive', models.BooleanField(default=False)),
                ('cid', models.CharField(max_length=16, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars_vw.carcolor')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars_vw.carmodel')),
            ],
            options={
                'ordering': ['cid', 'established'],
            },
        ),
    ]
