# Generated by Django 5.2 on 2025-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_vw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='car_pictures/')),
            ],
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='pictures',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='pictures',
            field=models.ManyToManyField(to='cars_vw.picture'),
        ),
    ]
