# Generated by Django 5.2 on 2025-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_vw', '0002_picture_remove_carmodel_pictures_carmodel_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(blank=True, upload_to='pictures/car_pictures/'),
        ),
    ]
