# Generated by Django 5.2 on 2025-04-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_vw', '0003_alter_picture_img'),
        ('users', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.address'),
        ),
    ]
