# Generated by Django 5.2 on 2025-04-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_vw', '0004_car_location2'),
        ('users', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location2',
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.address'),
        ),
    ]
