# Generated by Django 5.2 on 2025-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_vw', '0008_alter_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/pictures/car_models'),
        ),
    ]
