# Generated by Django 5.2 on 2025-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_vw', '0009_alter_picture_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/pictures/car_pictures/'),
        ),
    ]
